name: Backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "backend/**"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      wd-backend: ./backend
      wd-frontend: ./frontend

    steps:

    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: Setup .NET (5.0.x)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET (3.1.x)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.wd-backend}}

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.wd-backend}}

#    - name: Test
#      run: dotnet test --no-build --verbosity normal
#      working-directory: ${{env.wd-backend}}
