name: Frontend (simple)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "frontend/simple-client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/simple-client/**"


jobs:

  build:
    runs-on: ubuntu-latest
    env:
      wd-simpleclient: ./frontend/simple-client

    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
        working-directory: ${{env.wd-simpleclient}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./frontend/simple-client/deploy # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

